services:
  db:
    image: postgres:16-alpine
    container_name: pomidorowa-db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sh:/usr/local/bin/db-init.sh
    entrypoint: ["sh", "/usr/local/bin/db-init.sh"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: pomidorowa-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "until npx prisma db push; do echo 'Database not ready yet, retrying in 2 seconds...'; sleep 2; done && npm run start"

  frontend:
    build: ./frontend
    container_name: pomidorowa-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
